apply plugin: 'com.android.application'
//apply plugin: 'kotlin-android'

def ndk_version = '30.0.15729638'
def cmake_version = '4.1.2'

android {
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    /*kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17
    }*/
    compileSdk = 37
    buildToolsVersion = '37.0.0'
    defaultConfig {
        applicationId "com.mousebirdconsulting.autotester"
        minSdkVersion 26
        targetSdkVersion 37
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        /*
        devRelease {
            minifyEnabled false
            debuggable true
            jniDebuggable true
            renderscriptDebuggable false
            signingConfig signingConfigs.debug
            matchingFallbacks = ['release']
            proguardFiles getDefaultProguardFile('proguard-android.txt'), '../../../../library/maply/proguard-rules.pro'
        }
        */
        release {
            minifyEnabled false
            debuggable false
            jniDebuggable false
            /*renderscriptDebuggable false*/
        }
        debug {
            jniDebuggable true
            signingConfig signingConfigs.debug
        }
    }
    ndkVersion ndk_version
    externalNativeBuild {
        cmake {
            path file('../../../library/maply/CMakeLists.txt')
            version cmake_version
        }
    }
    namespace 'com.mousebirdconsulting.autotester'
}

dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(path: ':maply')
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'com.google.android.gms:play-services-location:21.4.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.squareup.okhttp3:okhttp:5.4.0'
}
repositories {
    mavenCentral()
}
