apply plugin: 'com.android.application'
//apply plugin: 'kotlin-android'

def ndk_version = '29.0.14206865'
def cmake_version = '4.1.2'

android {
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    /*kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17
    }*/
    compileSdk = 36
    buildToolsVersion = '36.0.0'
    defaultConfig {
        applicationId "com.mousebirdconsulting.autotester"
        minSdkVersion 23
        targetSdkVersion 36
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        /*
        devRelease {
            minifyEnabled false
            debuggable true
            jniDebuggable true
            renderscriptDebuggable false
            signingConfig signingConfigs.debug
            matchingFallbacks = ['release']
            proguardFiles getDefaultProguardFile('proguard-android.txt'), '../../../../library/maply/proguard-rules.pro'
        }
        */
        release {
            minifyEnabled false
            debuggable false
            jniDebuggable false
            /*renderscriptDebuggable false*/
        }
        debug {
            jniDebuggable true
            signingConfig signingConfigs.debug
        }
    }
    ndkVersion ndk_version
    externalNativeBuild {
        cmake {
            path file('../../../library/maply/CMakeLists.txt')
            version cmake_version
        }
    }
    namespace 'com.mousebirdconsulting.autotester'
}

dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(path: ':maply')
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.squareup.okhttp3:okhttp:5.3.2'
}
repositories {
    mavenCentral()
}
